### ISSUE TITLE
(UDP) client.close() in log callback prevents message send.

### ISSUE THREAD

**Issue by cdscott** [paulgrove/node-syslog-client#12]
When using UDP transport, calling client.close() from within the client.log callback function prevents the message from being sent. This appears to be a result of the client.log callback function being called synchronously in index.js, line 174, rather than from within the transport's async send function callback after the send occurs. This could be issue for TCP too, but definitely reproducible with UDP.

**Comment by paulgrove** [comment]
Thanks for this report, and sorry for the delay, I'll get this looked at.

**Comment by paulgrove** [comment]
Thanks I've merged this now and will close.  New release of npm module will be released today.
