### ISSUE TITLE
Error: getaddrinfo ENOTFOUND when specifying a hostname instead an IP

### ISSUE THREAD

**Issue by acanimal** [paulgrove/node-syslog-client#14]
If found that when using the client with hostname: `const client = syslog.createClient('my.host.name.here', options);` I get an `Error: getaddrinfo ENOTFOUND ...` error.

I found the problem is related with the way code chose the family IP at line: https://github.com/paulgrove/node-syslog-client/blob/master/index.js#L195

That makes that a non IP (like a hostname) be considered a IPv6.

The problem can be easily fixed changing:

```
var af = net.isIPv4(this.target) ? 4 : 6;
```

by

```
var af = net.isIPv6(this.target) ? 6 : 4;
```

This issue is important for me. Could you fix and publish a new npm package?
Thanks in advance.

**Comment by paulgrove** [comment]
Sorry about the delay for this, I'll get this change implemented in due course.
