### ISSUE TITLE
"connection timed out" Issues

### ISSUE THREAD

**Issue by santsys** [paulgrove/node-syslog-client#27]
It seems that when starting a TCP connection, to send log entries only, that a "connection timed out" error is always sent at least once. Continuing syslog events send fine.

It appears that there needs to be some function to "clear" the timeout event, or change how timeouts are handled?

Thank you!

**Comment by paulgrove** [comment]
Sorry for the late response - this is now fixed in master, I'll get a new release out to npm soon - thanks!
