### ISSUE TITLE
Add convenience wrapper functions for the various severity levels

### ISSUE THREAD

**Issue by stephenwvickers** [paulgrove/node-syslog-client#5]

**Comment by stephenwvickers** [comment]
Having reviewed this further, and discussed with my colleagues, I feel that this functionality should be part of a higher-level logging library.

**Comment by mccarthy** [comment]
Is this module compatible (as a transport) with something like Winston?  If so, then I agree.  

It would be worth mentioning in the readme that the intent is that this is not used directly, if that is in fact the intent.

**Comment by stephenwvickers** [comment]
That all depends on what you mean by "compatible".  It is compatible in the sense that it will work with winston if you write a wrapper library, like you would normally do for any library, for example:

https://www.npmjs.com/package/winston-couchdb

I don't think the presence of helper functions like the ones you implemented specify if a library can be used directly or not, that seems like a bad disposition to me.

In my experience most people will implement their own code to wrap around libraries such as this, and implement their required helper functions there - i.e. in an application logging sub-system that would be used by an entire application.

**Comment by mccarthy** [comment]
Thanks for the reply.  I am currently using node-syslog-client directly, which is why the helper functions make sense for my use-case.  However, I am using winston elsewhere so I might consider going that route later on.
