### ISSUE TITLE
Variable `key` in `_expandConstantObject()` missing `var` declaration

### ISSUE THREAD

**Issue by obarthel** [paulgrove/node-syslog-client#6]
In _expandConstantObject() there is a "var" missing here:

```
for (key in object)
    keys.push(key);
```

This ought to be changed, so that "key" does not become a global variable:

```
for (var key in object)
    keys.push(key);
```

Tiny change -- I didn't want to wrap this into a pull request ;-)

**Comment by stephenwvickers** [comment]
Thanks for picking this up, I will look at getting a new release done sometime this week.
